spring:
  security:
    oauth2:
      client:
        registration:
          # 구글 로그인 추가
          google:
            client-id: 71924857166-uq2ic54uvof4duaautm6gf924a0b0ak9.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile